### ISSUE TITLE
Simulink Style Problem

### ISSUE THREAD

**Issue by kmsaleh** [Mohabsaid/Power-to-Gas#4]
I've made the following comment to Joseph work, it applies to all students:

Buck_converter_with_Control_Model:
a- Do it in system/subsystem/subsubsystem... fashion (follow the AlphaRomeo example sent earlier) so that your model will be easy to follow.
b- Be generous in adding Notes to the model to explain what it is doing.
c- All signals must be labeled indicating name and units,

This comment for all students not Joseph only. share
I am not going to look at any model if it does not follow these guidelines as a minimum.

**Comment by JosephSamirFaik** [comment]
Thanks a lot Eng.Khalid for your commenting and mentoring.
Sure I will take all those points in my point of view in next time...
Please also see the Buck Converter in the Full Model of Fuel Cell you will see me made some of those points and let me know if there is any other problems or comments in it ..
Best Regards, Joseph.

**Comment by kmsaleh** [comment]
Try this link:
https://www.youtube.com/watch?v=BQ4YV3nqTe0

**Comment by JosephSamirFaik** [comment]
Thanks a lot Eng.Khalid ....
